package com.roxy.app

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.LocalActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.roxy.app.data.RoxyDatabase
import com.roxy.app.health.*
import com.roxy.app.notifications.*
import com.roxy.app.sync.*
import com.roxy.app.timeline.*
import com.roxy.app.usage.*
import java.util.concurrent.Executors

class MainActivity : ComponentActivity() { override fun onCreate(s: Bundle?) { super.onCreate(s); UsageCollectionScheduler.reconcile(applicationContext); setContent { RoxyApp(RoxyDatabase.create(applicationContext), PairingStore(applicationContext), this) } } }
private enum class Tab(val label: String) { HOME("Home"), ACTIVITY("Activity"), ALERTS("Alerts"), HEALTH("Health"), SETTINGS("Settings") }

@Composable private fun RoxyApp(db: RoxyDatabase, pairing: PairingStore, activity: ComponentActivity) {
    var tab by remember { mutableStateOf(Tab.HOME) }; var health by remember { mutableStateOf<List<CollectorHealth>>(emptyList()) }; var summary by remember { mutableStateOf<UsageSummaryResult?>(null) }; var summaryStatus by remember { mutableStateOf("Refreshing your private dashboard…") }
    var endpoint by remember { mutableStateOf(pairing.read()?.endpoint ?: "") }; var credential by remember { mutableStateOf("") }; var connection by remember { mutableStateOf(if (pairing.read()==null) "Not connected" else "Connected") }; var notifications by remember { mutableStateOf(NotificationPolicyStore(activity).isEnabled()) }; var notificationPackage by remember { mutableStateOf("") }; var notificationSummary by remember { mutableStateOf<NotificationSummaryResult?>(null) }; var notificationStatus by remember { mutableStateOf("Refresh to view metadata-only notification activity.") }
    val work = remember { Executors.newSingleThreadExecutor() }
    fun refreshHealth() = work.execute { val x=CollectorHealthReader.read(activity,db); android.os.Handler(android.os.Looper.getMainLooper()).post { health=x } }
    fun refreshSummary() { val p=pairing.read() ?: run { summaryStatus="Connect Roxy in Settings to load activity."; return }; work.execute { val x=UsageSummaryReader.read(p,java.time.LocalDate.now().toString()); android.os.Handler(android.os.Looper.getMainLooper()).post { summary=x; summaryStatus=if(x is UsageSummaryResult.Success) "Updated from your private Roxy service." else "Activity is temporarily unavailable." } } }
    fun refreshNotifications() { val p=pairing.read() ?: run { notificationStatus="Connect Roxy in Settings to load notification activity."; return }; notificationStatus="Refreshing notification activity…"; work.execute { val x=NotificationSummaryReader.read(p,java.time.LocalDate.now().toString()); android.os.Handler(android.os.Looper.getMainLooper()).post { notificationSummary=x; notificationStatus=if(x is NotificationSummaryResult.Success) "Updated from your private Roxy service." else "Notification activity is temporarily unavailable." } } }
    LaunchedEffect(Unit) { refreshHealth(); refreshSummary(); refreshNotifications() }
    MaterialTheme(colorScheme=darkColorScheme(primary=androidx.compose.ui.graphics.Color(0xFFAA9CFF),secondary=androidx.compose.ui.graphics.Color(0xFF51E4C0),surface=androidx.compose.ui.graphics.Color(0xFF15131F))) { Scaffold(bottomBar={ NavigationBar { Tab.entries.forEach { t -> NavigationBarItem(selected=tab==t,onClick={tab=t;if(t==Tab.HEALTH)refreshHealth()},icon={Text(if(tab==t)"●" else "○")},label={Text(t.label)}) } } }) { pad -> Column(Modifier.fillMaxSize().padding(pad).verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)) { Text("ROXY",style=MaterialTheme.typography.headlineLarge,fontWeight=FontWeight.Black); Text("PRIVATE CONTEXT · LIVE",color=MaterialTheme.colorScheme.secondary)
        when(tab) { Tab.HOME -> Home(summary,summaryStatus,health,::refreshSummary,::refreshHealth,activity); Tab.ACTIVITY -> Activity(summary,summaryStatus,::refreshSummary,activity); Tab.ALERTS -> Alerts(health.firstOrNull{it.collector=="notifications"},notifications,{notifications=it;NotificationPolicyStore(activity).setEnabled(it);refreshHealth()},activity,notificationSummary,notificationStatus,::refreshNotifications); Tab.HEALTH -> Health(health,::refreshHealth); Tab.SETTINGS -> Settings(endpoint,{endpoint=it},credential,{credential=it},connection,{runCatching{pairing.save(endpoint,credential);UsageCollectionScheduler.reconcile(activity);SyncScheduler.enqueue(activity)}.onSuccess{connection="Connected. Automatic collection is active.";refreshHealth()}.onFailure{connection="Enter a valid server address and pairing credential."}},activity,notificationPackage,{notificationPackage=it},{ val rule=NotificationPolicy.defaultRule(notificationPackage); if(rule==null) connection="Enter a valid package identifier." else { val store=NotificationPolicyStore(activity); store.saveRules(NotificationPolicy.update(store.rules(),rule.packageName,NotificationPackagePolicy.BLOCKED)); notificationPackage=""; connection="Notification metadata blocked for the selected app." } }) }
    } } }
}
@Composable private fun Home(s:UsageSummaryResult?,status:String,h:List<CollectorHealth>,refresh:()->Unit,health:()->Unit,a:ComponentActivity){ Box("Today","Real activity and system context, refreshed only when you ask."){Button(onClick=refresh){Text("Refresh dashboard")};Text(status);if(s is UsageSummaryResult.Success){Text("${s.totalMillis/60_000} min",style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.Bold);Text("Recorded activity today");s.apps.take(5).forEach{ x->Text("${UsageSummaryReader.resolveLabel(a,x.id).text}  ·  ${x.durationMillis/60_000} min")}}};Box("System pulse","Your collectors run automatically in the background."){Button(onClick=health){Text("Refresh health")};h.forEach{Text("${it.collector.replace('_',' ')} · ${it.state.replace('_',' ')}")}}}
@Composable private fun Activity(s:UsageSummaryResult?,status:String,refresh:()->Unit,a:ComponentActivity){Box("Activity analysis","Aggregate usage only — never app content."){Button(onClick=refresh){Text("Refresh activity")};Text(status);if(s is UsageSummaryResult.Success)s.apps.forEach{x->Text("${UsageSummaryReader.resolveLabel(a,x.id).text} — ${x.durationMillis/60_000} min",fontWeight=FontWeight.SemiBold)}else Text("No synced activity is available yet.")}}
@Composable private fun Alerts(h:CollectorHealth?,enabled:Boolean,set:(Boolean)->Unit,a:ComponentActivity,s:NotificationSummaryResult?,status:String,refresh:()->Unit){var analytics by remember{mutableStateOf<NotificationAnalyticsResult?>(null)};val worker=remember{Executors.newSingleThreadExecutor()};fun refreshAnalytics(){PairingStore(a).read()?.let{pair->worker.execute{val next=NotificationAnalyticsReader.read(pair);android.os.Handler(android.os.Looper.getMainLooper()).post{analytics=next}}}};LaunchedEffect(Unit){refreshAnalytics()};Box("Notification context","Notifications arrive by Android callback, not a timer. This timeline is metadata only."){Text("Status: ${h?.state?.replace('_',' ') ?: "checking"}");Button(onClick={refresh();refreshAnalytics()}){Text("Refresh notification activity")};Text(status);if(s is NotificationSummaryResult.Success){Text("${s.count} events today",style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);if(s.items.isEmpty())Text("No notification metadata has arrived today.") else s.items.forEach{x->Text("${UsageSummaryReader.resolveLabel(a,x.packageName).text} · ${if(x.type=="notification.posted")"arrived" else "cleared"}")}};when(val result=analytics){is NotificationAnalyticsResult.Success->Box("Today’s signal","Numbers are calculated from metadata already collected by Roxy."){Text("${result.value.postedCount} arrived · ${result.value.removedCount} cleared");Text(if(result.value.busiestHour==null)"No busy hour yet." else "Busiest hour: ${result.value.busiestHour}:00");Text(if(result.value.topSourceCount==0)"No top source yet." else "Top source: ${UsageSummaryReader.resolveLabel(a,result.value.topSourcePackage ?: "").text} · ${result.value.topSourceCount} events")};is NotificationAnalyticsResult.Error->Text("Analytics will appear when your private service has the latest Roxy update.",style=MaterialTheme.typography.bodySmall);null->Text("Loading today’s analytics…",style=MaterialTheme.typography.bodySmall)};Button(onClick={set(!enabled)}){Text(if(enabled)"Pause notification metadata" else "Enable notification metadata")};Button(onClick={a.startActivity(NotificationAccess.settingsIntent())}){Text("Manage notification access")};Text("Titles and message text never appear here.")}}
@Composable private fun Health(h:List<CollectorHealth>,refresh:()->Unit){Box("Collector health","Safe state, queue, and failure information — no personal activity details."){Button(onClick=refresh){Text("Refresh health")};h.forEach{x->HorizontalDivider();Text(x.collector.replace('_',' '),fontWeight=FontWeight.Bold);Text("${x.state.replace('_',' ')} · ${x.pendingCount} waiting to sync");Text(x.failureCode ?: "No current failure")}}}
@Composable private fun Settings(endpoint:String,onEndpoint:(String)->Unit,credential:String,onCredential:(String)->Unit,status:String,connect:()->Unit,a:ComponentActivity,pkg:String,onPkg:(String)->Unit,approve:()->Unit){Box("Connection","One-time setup for your private Roxy service."){OutlinedTextField(endpoint,onEndpoint,label={Text("Roxy server address")},modifier=Modifier.fillMaxWidth());OutlinedTextField(credential,onCredential,label={Text("Pairing credential")},modifier=Modifier.fillMaxWidth());Button(onClick=connect){Text("Connect Roxy")};Text(status)};Box("Notification metadata","Metadata is collected by default after Android access is granted. Notification text is never collected here."){OutlinedTextField(pkg,onPkg,label={Text("Package identifier to block")},modifier=Modifier.fillMaxWidth());Button(onClick=approve){Text("Block this app’s metadata")};Text("Use this only when you want to exclude a specific app. The collector can also be paused from Alerts.",style=MaterialTheme.typography.bodySmall)};Box("Permissions","You remain in control of each collector."){Button(onClick={a.startActivity(UsageAccess.settingsIntent())}){Text("Manage usage access")};Button(onClick={a.startActivity(NotificationAccess.settingsIntent())}){Text("Manage notification access")}}}
@Composable private fun Box(title:String,detail:String,content:@Composable ColumnScope.()->Unit){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text(title,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text(detail);content()}}}
