package com.roxy.app

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.LocalActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.foundation.shape.RoundedCornerShape
import com.roxy.app.data.RoxyDatabase
import com.roxy.app.health.*
import com.roxy.app.notifications.*
import com.roxy.app.sync.*
import com.roxy.app.timeline.*
import com.roxy.app.usage.*
import java.util.concurrent.Executors

class MainActivity : ComponentActivity() { override fun onCreate(s: Bundle?) { super.onCreate(s); UsageCollectionScheduler.reconcile(applicationContext); setContent { RoxyApp(RoxyDatabase.create(applicationContext), PairingStore(applicationContext), this) } } }
private enum class Tab(val label: String) { HOME("Home"), ACTIVITY("Activity"), ALERTS("Alerts"), HEALTH("Health"), SETTINGS("Settings") }

@Composable private fun RoxyApp(db: RoxyDatabase, pairing: PairingStore, activity: ComponentActivity) {
    var tab by remember { mutableStateOf(Tab.HOME) }; var health by remember { mutableStateOf<List<CollectorHealth>>(emptyList()) }; var summary by remember { mutableStateOf<UsageSummaryResult?>(null) }; var summaryStatus by remember { mutableStateOf("Refreshing your private dashboard…") }
    var endpoint by remember { mutableStateOf(pairing.read()?.endpoint ?: "") }; var credential by remember { mutableStateOf("") }; var connection by remember { mutableStateOf(if (pairing.read()==null) "Not connected" else "Connected") }; var notifications by remember { mutableStateOf(NotificationPolicyStore(activity).isEnabled()) }; var notificationPackage by remember { mutableStateOf("") }; var notificationSummary by remember { mutableStateOf<NotificationSummaryResult?>(null) }; var notificationStatus by remember { mutableStateOf("Refresh to view metadata-only notification activity.") }
    val work = remember { Executors.newSingleThreadExecutor() }
    fun refreshHealth() = work.execute { val x=CollectorHealthReader.read(activity,db); android.os.Handler(android.os.Looper.getMainLooper()).post { health=x } }
    fun refreshSummary() { val p=pairing.read() ?: run { summaryStatus="Connect Roxy in Settings to load activity."; return }; work.execute { val x=UsageSummaryReader.read(p,java.time.LocalDate.now().toString()); android.os.Handler(android.os.Looper.getMainLooper()).post { summary=x; summaryStatus=if(x is UsageSummaryResult.Success) "Updated from your private Roxy service." else "Activity is temporarily unavailable." } } }
    fun refreshNotifications() { val p=pairing.read() ?: run { notificationStatus="Connect Roxy in Settings to load notification activity."; return }; notificationStatus="Refreshing notification activity…"; work.execute { val x=NotificationSummaryReader.read(p,java.time.LocalDate.now().toString()); android.os.Handler(android.os.Looper.getMainLooper()).post { notificationSummary=x; notificationStatus=if(x is NotificationSummaryResult.Success) "Updated from your private Roxy service." else "Notification activity is temporarily unavailable." } } }
    LaunchedEffect(Unit) { refreshHealth(); refreshSummary(); refreshNotifications() }
    MaterialTheme(colorScheme=darkColorScheme(primary=androidx.compose.ui.graphics.Color(0xFFAA9CFF),secondary=androidx.compose.ui.graphics.Color(0xFF51E4C0),surface=androidx.compose.ui.graphics.Color(0xFF15131F))) { Scaffold(bottomBar={ NavigationBar { Tab.entries.forEach { t -> NavigationBarItem(selected=tab==t,onClick={tab=t;if(t==Tab.HEALTH)refreshHealth()},icon={Text(if(tab==t)"●" else "○")},label={Text(t.label)}) } } }) { pad -> Column(Modifier.fillMaxSize().padding(pad).verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)) { Text("ROXY",style=MaterialTheme.typography.headlineLarge,fontWeight=FontWeight.Black); Text("PRIVATE CONTEXT · LIVE",color=MaterialTheme.colorScheme.secondary)
        when(tab) { Tab.HOME -> Home(summary,summaryStatus,health,::refreshSummary,::refreshHealth,activity); Tab.ACTIVITY -> Activity(summary,summaryStatus,::refreshSummary,activity); Tab.ALERTS -> Alerts(health.firstOrNull{it.collector=="notifications"},notifications,{notifications=it;NotificationPolicyStore(activity).setEnabled(it);refreshHealth()},activity,notificationSummary,notificationStatus,::refreshNotifications); Tab.HEALTH -> Health(health,::refreshHealth); Tab.SETTINGS -> Settings(endpoint,{endpoint=it},credential,{credential=it},connection,{runCatching{pairing.save(endpoint,credential);UsageCollectionScheduler.reconcile(activity);SyncScheduler.enqueue(activity)}.onSuccess{connection="Connected. Automatic collection is active.";refreshHealth()}.onFailure{connection="Enter a valid server address and pairing credential."}},activity,notificationPackage,{notificationPackage=it},{ val rule=NotificationPolicy.defaultRule(notificationPackage); if(rule==null) connection="Enter a valid package identifier." else { val store=NotificationPolicyStore(activity); store.saveRules(NotificationPolicy.update(store.rules(),rule.packageName,NotificationPackagePolicy.BLOCKED)); notificationPackage=""; connection="Notification metadata blocked for the selected app." } }) }
    } } }
}
private fun duration(m:Long)="${m/3_600_000}h ${(m%3_600_000)/60_000}m"
@Composable private fun Home(s:UsageSummaryResult?,status:String,h:List<CollectorHealth>,refresh:()->Unit,health:()->Unit,a:ComponentActivity){ Box("Today at a glance","A lightweight private snapshot."){Button(onClick=refresh){Text("Refresh dashboard")};Text(status);if(s is UsageSummaryResult.Success){Text(duration(s.totalMillis),style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.Black);Text("Recorded device activity today");s.apps.take(3).forEachIndexed{i,x->DurationMeter("${i+1}. ${UsageSummaryReader.resolveLabel(a,x.id).text}",x.durationMillis,s.totalMillis,Color(0xFFAA9CFF))}}};Box("System pulse","Collector health and sync readiness."){Button(onClick=health){Text("Refresh health")};h.forEach{Text("${it.collector.replace('_',' ')} · ${it.state.replace('_',' ')}")}}}
@Composable private fun Activity(s:UsageSummaryResult?,status:String,refresh:()->Unit,a:ComponentActivity){Box("Activity ranking","A ranked breakdown of aggregate on-device time."){Button(onClick=refresh){Text("Refresh activity")};Text(status);if(s is UsageSummaryResult.Success){Text("${duration(s.totalMillis)} total recorded",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Black);s.apps.forEachIndexed{i,x->DurationMeter("#${i+1}  ${UsageSummaryReader.resolveLabel(a,x.id).text}",x.durationMillis,s.totalMillis,if(i==0)Color(0xFF51E4C0) else Color(0xFFAA9CFF))}}else Text("No synced activity is available yet.")}}
@Composable private fun DurationMeter(label:String,value:Long,total:Long,color:Color){Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Row{Text(label,modifier=Modifier.weight(1f),fontWeight=FontWeight.SemiBold,maxLines=1,overflow=TextOverflow.Ellipsis);Text(duration(value),color=color,fontWeight=FontWeight.Bold)};LinearProgressIndicator(progress={if(total==0L)0f else value.toFloat()/total},color=color,trackColor=color.copy(alpha=.16f),modifier=Modifier.fillMaxWidth().height(9.dp).clip(RoundedCornerShape(9.dp)))}}
@Composable private fun Alerts(h:CollectorHealth?,enabled:Boolean,set:(Boolean)->Unit,a:ComponentActivity,s:NotificationSummaryResult?,status:String,refresh:()->Unit){var analytics by remember{mutableStateOf<NotificationAnalyticsResult?>(null)};var period by remember{mutableStateOf("day")};val worker=remember{Executors.newSingleThreadExecutor()};fun refreshAnalytics(){PairingStore(a).read()?.let{pair->worker.execute{val next=NotificationAnalyticsReader.read(pair,period=period);android.os.Handler(android.os.Looper.getMainLooper()).post{analytics=next}}}};LaunchedEffect(period){refreshAnalytics()};Box("Notification intelligence","Live aggregate signals from Android callbacks. Never a message count."){Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf("day","week","month").forEach{p->FilterChip(selected=period==p,onClick={period=p},label={Text(p.replaceFirstChar{it.uppercase()})})}};Text("Status: ${h?.state?.replace('_',' ') ?: "checking"}",color=MaterialTheme.colorScheme.secondary);Button(onClick={refresh();refreshAnalytics()}){Text("Refresh activity")};Text(status);when(val result=analytics){is NotificationAnalyticsResult.Success->{val v=result.value;Text("${v.count} activity events",style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.Black);SignalMeter("Arrivals",v.postedCount,v.count,Color(0xFF7C9CFF));SignalMeter("Updates",v.updatedCount,v.count,Color(0xFFBB86FC));SignalMeter("Cleared",v.removedCount,v.count,Color(0xFF55E6C1));AnalyticsDetails(v,a)};is NotificationAnalyticsResult.Error->Text("Analytics are temporarily unavailable.",style=MaterialTheme.typography.bodySmall);null->Text("Loading activity signals…",style=MaterialTheme.typography.bodySmall)};Button(onClick={set(!enabled)}){Text(if(enabled)"Pause notification metadata" else "Enable notification metadata")};Button(onClick={a.startActivity(NotificationAccess.settingsIntent())}){Text("Manage notification access")};Text("Titles and message text never appear here.",style=MaterialTheme.typography.bodySmall)}}
@Composable private fun AnalyticsDetails(v:NotificationAnalytics,a:ComponentActivity){NotificationPatterns.compare(v.count,v.history.map{it.count})?.let{Box("Activity comparison",it.explanation){Text("Evidence · ${it.currentCount} now · baseline ${it.baselineCount} · ${it.comparedPeriods} prior days",style=MaterialTheme.typography.bodySmall)}};var selectedHour by remember{mutableStateOf<Int?>(null)};var expanded by remember{mutableStateOf(false)};val scope=if(v.period=="day")"today" else "across this ${v.period}";Text("Hourly rhythm",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);Text("Each hour is aggregated $scope.",style=MaterialTheme.typography.bodySmall);Box{OutlinedButton(onClick={expanded=true},modifier=Modifier.fillMaxWidth()){Text(selectedHour?.let{"${it.toString().padStart(2,'0')}:00 $scope"} ?: "Select an hour")};DropdownMenu(expanded=expanded,onDismissRequest={expanded=false}){v.hourly.forEach{x->DropdownMenuItem(text={Text("${x.hour.toString().padStart(2,'0')}:00 $scope · ${x.count} events")},onClick={selectedHour=x.hour;expanded=false})}}};selectedHour?.let{hour->val sources=v.hourlySources.firstOrNull{it.hour==hour}?.sources.orEmpty();Text("Top sources at ${hour.toString().padStart(2,'0')}:00 $scope",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);if(sources.isEmpty())Text("This hour has no source breakdown yet.") else sources.take(5).forEach{x->SignalMeter(UsageSummaryReader.resolveLabel(a,x.packageName).text,x.count,sources.sumOf{it.count},Color(0xFF51E4C0))}};Text("Top sources",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);v.sources.take(5).forEach{x->SignalMeter(UsageSummaryReader.resolveLabel(a,x.packageName).text,x.count,v.count,Color(0xFFAA9CFF))};if(v.sources.size>5)Text("Showing the top 5 sources.",style=MaterialTheme.typography.bodySmall);if(v.bursts.isNotEmpty())Text("Burst windows · ${v.bursts.joinToString { "${it.startHour}:00 (${it.count})" }}");Text("Coverage · ${v.completeness.reason.replace('_',' ')}",style=MaterialTheme.typography.bodySmall)}
@Composable private fun SignalMeter(label:String,value:Int,total:Int,color:Color){Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Row{Text(label,modifier=Modifier.weight(1f),fontWeight=FontWeight.SemiBold);Text(value.toString(),color=color,fontWeight=FontWeight.Bold)};LinearProgressIndicator(progress={if(total==0)0f else value.toFloat()/total},color=color,trackColor=color.copy(alpha=.16f),modifier=Modifier.fillMaxWidth().height(9.dp).clip(RoundedCornerShape(9.dp)))}}
@Composable private fun Health(h:List<CollectorHealth>,refresh:()->Unit){Box("Collector health","Safe state, queue, and failure information — no personal activity details."){Button(onClick=refresh){Text("Refresh health")};h.forEach{x->HorizontalDivider();Text(x.collector.replace('_',' '),fontWeight=FontWeight.Bold);Text("${x.state.replace('_',' ')} · ${x.pendingCount} waiting to sync");Text(x.failureCode ?: "No current failure")}}}
@Composable private fun Settings(endpoint:String,onEndpoint:(String)->Unit,credential:String,onCredential:(String)->Unit,status:String,connect:()->Unit,a:ComponentActivity,pkg:String,onPkg:(String)->Unit,approve:()->Unit){Box("Connection","One-time setup for your private Roxy service."){OutlinedTextField(endpoint,onEndpoint,label={Text("Roxy server address")},modifier=Modifier.fillMaxWidth());OutlinedTextField(credential,onCredential,label={Text("Pairing credential")},modifier=Modifier.fillMaxWidth());Button(onClick=connect){Text("Connect Roxy")};Text(status)};Box("Notification metadata","Metadata is collected by default after Android access is granted. Notification text is never collected here."){OutlinedTextField(pkg,onPkg,label={Text("Package identifier to block")},modifier=Modifier.fillMaxWidth());Button(onClick=approve){Text("Block this app’s metadata")};Text("Use this only when you want to exclude a specific app. The collector can also be paused from Alerts.",style=MaterialTheme.typography.bodySmall)};Box("Permissions","You remain in control of each collector."){Button(onClick={a.startActivity(UsageAccess.settingsIntent())}){Text("Manage usage access")};Button(onClick={a.startActivity(NotificationAccess.settingsIntent())}){Text("Manage notification access")}}}
@Composable private fun Box(title:String,detail:String,content:@Composable ColumnScope.()->Unit){Card(Modifier.fillMaxWidth(),shape=RoundedCornerShape(24.dp),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant.copy(alpha=.55f)),elevation=CardDefaults.cardElevation(defaultElevation=6.dp)){Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text(title,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Black);Text(detail,color=MaterialTheme.colorScheme.onSurfaceVariant);content()}}}
